### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nharbo**

### CODE REVIEW

**Comment by pbodsk** [comment]
@nharbo I've changed bits and pieces of the README, nothing too serious I hope 😄 

Good work

**Review by pbodsk — COMMENTED** [review]
As mentioned, I've changed bits and pieces here and there. I hope it is for the better

**Comment by nharbo** [comment]
Looks great to me @pbodsk :)

**Comment by pbodsk** [comment]
Lets hold back the merging till the other PRs has been merged. Just to keep README and code aligned

**Pull request merged**
